<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-8ETCIKP" failures="2" tests="2" name="Default test(failed)" time="0.22" errors="0" timestamp="2023-12-25T17:32:47 IST">
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase02" time="0.052">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.FailedRetryLogic.TestCaseExample.TestCase02(TestCaseExample.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase01" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.FailedRetryLogic.TestCaseExample.TestCase01(TestCaseExample.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase03" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase03 -->
</testsuite> <!-- Default test(failed) -->
