<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8ETCIKP" failures="2" tests="9" name="Test" time="0.38" errors="0" timestamp="2023-12-25T17:53:08 IST">
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase01" time="0.048">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase01" time="0.006">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase01" time="0.002">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase01" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.FailedRetryLogic.TestCaseExample.TestCase01(TestCaseExample.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase02" time="0.008">
    <skipped/>
  </testcase> <!-- TestCase02 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase02" time="0.007">
    <skipped/>
  </testcase> <!-- TestCase02 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase02" time="0.004">
    <skipped/>
  </testcase> <!-- TestCase02 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase02" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.FailedRetryLogic.TestCaseExample.TestCase02(TestCaseExample.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="com.FailedRetryLogic.TestCaseExample" name="TestCase03" time="0.002"/>
</testsuite> <!-- Test -->
